name: Pylint

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pylint-exit
    - name: Analysing the code with pylint
      run: |
        pylint TwitchWebsocket | tee pylint.txt
    - name: Upload pylint.txt as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pylint_report
        path: pylint.txt
